replicaCount: 1
image:
  repository: ghcr.io/hashilbasheer/static-cicd-demo
  tag: cab3086
service:
  port: 80
httproute:
  enabled: true
  gatewayName: external-gateway
  gatewayNamespace: nginx-gateway
  sectionName: https
  hostname: static-app.hashil.online
