apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-app
  labels:
    app: static-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: static-app
  template:
    metadata:
      labels:
        app: static-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: static-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80