apiVersion: v1
kind: Service
metadata:
  name: static-app
spec:
  type: ClusterIP
  selector:
    app: static-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
